# Generated by Django 4.2.1 on 2023-07-25 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paperstoremodel',
            name='paper',
            field=models.ImageField(blank=True, null=True, upload_to='all_papers/'),
        ),
    ]
